name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: CISE_Repos/CISE_Repos/worksheet2

      - name: Run tests
        run: npm test
        working-directory: CISE_Repos/CISE_Repos/worksheet2

      - name: Build
        run: npm run build
        working-directory: CISE_Repos/CISE_Repos/worksheet2